COLS_ENLACE = "D,D2,D4"
COLS_REGLAS = "R1"
COLS_ROUTING = "CR"
COLS_CONEXIONES = "n4,n16,n64"
#PARA AGENTES COOPERADORES:
TAM_ENLACES=["D","D2","D4"]
REGLAS=["R1"]
TOPOLOGIAS=["malla8x8"]
ALG_ENCAMINAMIENTO=["CR"]

#PARA AGENTES SEMI-COOPERADORES:
TAM_ENLACES_SC=["D","D2","D4","D8","D16"]
REGLAS_SC=[]#["R1","R2","R3"]
TOPOLOGIAS_SC=["anillo1500","malla50x50"]
CONEXIONES_SC=["n4","n16","n64"]

#PARA AGENTES DEGRADACION:
DEGRADACION=["Fallas","Ataques"]